### ISSUE TITLE
Needs to be updated to keras 2.0 API

### ISSUE THREAD

**Issue by thomasj02** [bstriner/keras-tqdm#10]
The Keras 2.0 API makes a bunch of changes, but primarily it doesn't seem to expose nb_samples anymore and keras-tqdm relies on that.

**Comment by b-knight** [comment]
I have been consistently getting an error `KeyError: 'nb_epoch'` ...I imagine because Keras 2 renamed `nb_epoch` to `epochs.`

**Comment by bstriner** [comment]
@thomasj02 and @b-knight Sorry guys! Got some projects due this week. Will try to make the updates by this weekend.

Cheers

**Comment by bstriner** [comment]
Current version on github supports keras 1 and 2. Setup Travis so it is testing keras 1 and 2 and python 2.7 and 3.5. Will get that version to pypi eventually. Please let me know if you guys have any remaining issues.

**Comment by b-knight** [comment]
Thanks Ben! It looks great to see it in action. Can you use it in Keras' model.evaluate() and model.predict() functions as well?

**Comment by bstriner** [comment]
@b-knight predict/evaluate would need some updates to keras to add callbacks but it is on my to-do list. Cheers!
