### ISSUE TITLE
epoch tracking for fit_generator

### ISSUE THREAD

**Issue by simonm3** [bstriner/keras-tqdm#11]
Great package. really useful. however does not update the epoch bar when using fit_generator. Looks like the code has started to be adapted for that but is not quite finished? Is that right?

Can I just lower the number of samples per epoch to get more frequent updates? Or will that have side effects?

**Comment by bstriner** [comment]
@simonm3 code should be running correctly. Can you give me some details?
* Keras 1.2 or 2
* Python 2 or 3
* console or Jupyter
* PyPI `keras-tqdm` or the development branch

Try `jupyter notebook` and the notebook in the `examples` directory. Both the `fit` and `fit_generator` examples should be showing 2 progress bars, 1 for training and 1 for the epoch. Please let me know if the examples work correctly for you, or if your custom code is having issues.

Cheers

**Comment by simonm3** [comment]
keras 1.1.2
python 3.6
jupyter
pypi keras-tqdm

I get the two progress bars. But they only update once at the end of each
epoch. And if there are 6 epochs they all say 6/6 at the end. I will try
the examples tomorrow but don't think am doing anything especially weird.

**Comment by bstriner** [comment]
I'll give a quick try with keras 1.1.2 on py 2.7.

**Comment by bstriner** [comment]
@simonm3 thanks for the find! Samples and epochs were swapped for Keras 1. If you install the current git master it should work for you. Please let me know and I can release the fix to PyPI.

**Comment by bstriner** [comment]
@simonm3 just dropped keras-tqdm 2.0.1 on PyPI. If a `pip install keras-tqdm --upgrade` fixes your problem please close the issue.

Cheers

**Comment by simonm3** [comment]
Perfect thanks.
