### ISSUE TITLE
Getting error "metric function identifier" error

### ISSUE THREAD

**Issue by gauss256** [bstriner/keras-tqdm#13]
I get the following error in a notebook, and a similar error when running the corresponding code at the command line:

`ValueError: ('Could not interpret metric function identifier:', <keras_tqdm.tqdm_notebook_callback.TQDMNotebookCallback object at 0x7eff8b8872b0>)`

The code I am using is:
```
from keras_tqdm import TQDMNotebookCallback
...
model.compile(loss='binary_crossentropy', optimizer='adam', verbose=0, metrics=[TQDMNotebookCallback()])
```

**Comment by paduel** [comment]
I think you must use **callbacks**=[TQDMNotebookCallback()],   it is not a metric function.

**Comment by gauss256** [comment]
Yes, duh! And your observation led me to fix another couple of errors. All working now.

Perfect timing too. I'd put the project aside for a bit but picked it up again just today. Thanks!
